# COPY into Streamlit Cloud > App > Settings > Secrets (do NOT commit)
APP_NAME = "GIG Takaful HR Training Intelligence"
DATA_BACKEND = "csv"        # "csv" or "supabase"

# Supabase (optional)
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
SUPABASE_SERVICE_KEY = ""   # not required for read-only
SUPABASE_SCHEMA = "public"
SUPABASE_EMP_TABLE = "employees"